version: '3.8'

services:

  php-apache-design:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/html

volumes:
  php-apache-design: